# Generated by Django 5.2.1 on 2025-05-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=100, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(help_text='Email del cliente', max_length=100, verbose_name='Email del cliente')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientsReservs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SitioTuristico', models.CharField(help_text='Nombre del sitio turistico', max_length=100, verbose_name='Nombre del sitio turistico')),
                ('ClientsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('ReservationsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservations')),
            ],
            options={
                'verbose_name': 'ClientReserv',
                'verbose_name_plural': 'ClientsReservs',
            },
        ),
    ]
