# Generated by Django 5.2.1 on 2025-05-23 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateReserv', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reservacion')),
                ('NumDias', models.IntegerField(default=1, help_text='Numero de dias', verbose_name='Numero de dias')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor', max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
