# Generated by Django 5.2.1 on 2025-05-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reserva'},
        ),
    ]
