# Generated by Django 5.0.14 on 2025-05-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
